[project]
name = "xtrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.6.4",
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "httpx>=0.28.1",
]
